channels:
  default:
    home: [1, 2, 3, 4, 5, 6]
    pricing: [1, 4, 2, 3]
    checkout: [1, 3, 4, 2, 5, 6]
    payment: [4, 3, 2, 1]

  ottopeek:
    home: [1, 2, 3, 4, 5, 6]
    pricing: [2, 1, 3, 4]
    checkout: [1, 4, 2, 3]
    payment: [3, 2, 4, 1]


  voiroto:
    home: [1, 6, 2, 3, 4, 5]
    pricing: [2, 1, 3, 4]
    checkout: [1, 4, 2, 3]
    payment: [3, 2, 4, 1]
