channels:
  default:
    home: [1, 2, 3, 4]
    pricing: [1, 2, 3, 4]
    checkout: [2, 1, 3, 4]
    payment: [4, 3, 2, 1]

  ottokpeek:
    home: [4, 3, 2, 1]
    pricing: [2, 1, 3, 4]
    checkout: [1, 4, 2, 3]
    payment: [3, 2, 4, 1]
