channels:
  default:
    index: [5, 3, 2, 4, 1]
    pricing: [1, 4, 2, 3]
    checkout: [1, 3, 4, 2, 5, 6]
    payment: [4, 3, 2, 1]

  ottokpeek:
    index: [4, 3, 2, 1]
    pricing: [2, 1, 3, 4]
    checkout: [1, 4, 2, 3]
    payment: [3, 2, 4, 1]
